/*
 * Auto-generated by Frida. Please modify to match the signature of CC_SHA256.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('CC_SHA256() 🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽');
    var len;
    try {
        len = args[1].toInt32 ? args[1].toInt32() : parseInt(args[1]);
    } catch (e) {
        log('长度转换错误: ' + e.message);
        len = 32; // 默认长度
    }
    try {
        var inputStr = args[0].readCString(len);
        log('input: ' + inputStr);
    } catch (e) {
        if (typeof hexdump === 'function') {
            log(hexdump(args[0], {
                length: len,
                header: true,
                ansi: true
            }));
        }
    }
  },

  onLeave(log, retval, state) {
    var sha256_digest = hexdump(retval, {length: 32});
    var hexified = " ";
    var raw_array = sha256_digest.split("\n");
    for (var a = 0; a < raw_array.length; a++) {
        var line_array = raw_array[a].split(" ");
        for (var b = 1; b < line_array.length - 1; b++) {
            if (line_array[b].length === 2) {
                hexified += line_array[b];
                hexified = hexified.trim();
            }
        }
    }
    log('output: ' + hexified);
    log('CC_SHA256() 🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼\n');
  }
});
