/*
 * Auto-generated by Frida. Please modify to match the signature of CCCrypt.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

// 通用的十六进制转换函数
function parseHexDump(hexdumpResult) {
    var hexified = " ";
    var raw_array = hexdumpResult.split("\n");
    for (var a = 0; a < raw_array.length; a++) {
        var line_array = raw_array[a].split(" ");
        for (var b = 1; b < line_array.length - 1; b++) {
            if (line_array[b].length === 2) {
                hexified += line_array[b];
                hexified = hexified.trim();
            }
        }
    }
    return hexified;
}

defineHandler({
    onEnter(log, args, state) {
        log('CCCrypt() 🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽');

        // 保存参数到state
        this.operation = args[0]
        this.CCAlgorithm = args[1]
        this.CCOptions = args[2]
        this.keyBytes = args[3]
        this.keyLength = args[4]
        this.ivBuffer = args[5]
        this.inBuffer = args[6]
        this.inLength = args[7]
        this.outBuffer = args[8]
        this.outLength = args[9]
        this.outCountPtr = args[10]

        // log('Backtrace:\n' + Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n\t'));

    },

    onLeave(log, retval, state) {
        if (this.operation == 0) {
            // Show the buffers here if this an encryption operation

            // console.log("[+] CCAlgorithm: " + this.CCAlgorithm);
            if (this.CCAlgorithm == 0x0) { log("CCAlgorithm: " + this.CCAlgorithm + " --> AES Encrypt"); }
            if (this.CCAlgorithm == 0x1) { log("CCAlgorithm: " + this.CCAlgorithm + " --> DES Encrypt"); }
            if (this.CCAlgorithm == 0x2) { log("CCAlgorithm: " + this.CCAlgorithm + " --> 3DES Encrypt"); }


            // enum {
            //     /* options for block ciphers */
            //     kCCOptionPKCS7Padding   = 0x0001,
            //     kCCOptionECBMode        = 0x0002
            //     /* stream ciphers currently have no options */
            // };
            // typedef uint32_t CCOptions;
            if (this.CCOptions == 0x0 || this.CCOptions == 0x1) { log("CCOptions: " + this.CCOptions + " --> mode CBC"); }
            if (this.CCOptions == 0x2 || this.CCOptions == 0x3) { log("CCOptions: " + this.CCOptions + " --> mode ECB"); } // kCCOptionPKCS7Padding | kCCOptionECBMode == 0x03
            // if (this.CCOptions != 0x1 && this.CCOptions != 0x3) {console.log("[+] CCOptions: " + this.CCOptions);}


            try {
              // log(Memory.readByteArray(this.inBuffer, this.inLength.toInt32()));
                // console.log("[+] Before Encrypt: " + Memory.readUtf8String(this.inBuffer, this.inLength.toInt32()));
                log("Before Encrypt1: " + Memory.readUtf8String(this.inBuffer, this.inLength.toInt32()));
            } catch (e) {
                var ByteArray = Memory.readByteArray(this.inBuffer, this.inLength.toInt32());
                var uint8Array = new Uint8Array(ByteArray);
                // console.log("[+] uint8Array: " + uint8Array);

                var str = "";
                for(var i = 0; i < uint8Array.length; i++) {
                    var hextemp = (uint8Array[i].toString(16))
                    if(hextemp.length == 1){
                        hextemp = "0" + hextemp
                    }
                        str += hextemp + " ";
                }

                console.log("Before Encrypt2: " + str); // 打印hex,非可见ascii范围
            }

            log(Memory.readByteArray(this.keyBytes, this.keyLength.toInt32()));
            if (this.keyLength.toInt32() == 16) { log("[+] KEY Length --> 128"); }
            if (this.keyLength.toInt32() == 24) { log("[+] KEY Length --> 192"); }
            if (this.keyLength.toInt32() == 32) { log("[+] KEY Length --> 256"); }
            try {
                // console.log("[+] KEY: " + Memory.readUtf8String(this.keyBytes, this.keyLength.toInt32()));
                log("KEY: " + Memory.readUtf8String(this.keyBytes, this.keyLength.toInt32()));
            } catch (e) {
                var ByteArray = Memory.readByteArray(this.keyBytes, this.keyLength.toInt32());
                var uint8Array = new Uint8Array(ByteArray);
                // console.log("[+] uint8Array: " + uint8Array);

                var str = "";
                for (var i = 0; i < uint8Array.length; i++) {
                    var hextemp = (uint8Array[i].toString(16))
                    if (hextemp.length == 1) {
                        hextemp = "0" + hextemp
                    }
                    str += hextemp + " ";
                }

                // console.log("[+] KEY: " + str); // 打印hex,非可见ascii范围
                LOG("[+] KEY: " + str, { c: Color.Gray });
            }

            if (this.CCOptions == 0x0 || this.CCOptions == 0x1) {
                console.log(Memory.readByteArray(this.ivBuffer, 16));
                try {
                    // console.log("[+] IV: " + Memory.readUtf8String(this.ivBuffer, this.keyLength.toInt32()));
                    log("[+] IV: " + Memory.readUtf8String(this.ivBuffer, 16));
                } catch (e) {
                    var ByteArray = Memory.readByteArray(this.ivBuffer, 16);
                    var uint8Array = new Uint8Array(ByteArray);

                    var str = "";
                    for (var i = 0; i < uint8Array.length; i++) {
                        var hextemp = (uint8Array[i].toString(16))
                        if (hextemp.length == 1) {
                            hextemp = "0" + hextemp
                        }
                        str += hextemp + " ";
                    }

                    // console.log("[+] IV: " + str); // 打印hex,非可见ascii范围
                    LOG("[+] IV: " + str, { c: Color.Gray });
                }
            }

            // console.log(Memory.readByteArray(this.outBuffer, Memory.readUInt(this.outCountPtr))); // 打印hex,非可见ascii范围
            var array = new Uint8Array(Memory.readByteArray(this.outBuffer, Memory.readUInt(this.outCountPtr)));
            // console.log("[+] After Encrypt: " + base64encode(bin2string(array)));
            LOG("[+] After Encrypt: " + base64encode(bin2string(array)), { c: Color.Gray });

            console.log("[-] --------------------------------------------------------------\n");
        }

        if (this.operation == 1) {
            // Show the buffers here if this a decryption operation

            // console.log("inLength: " + this.inLength.toInt32());
            // console.log("outLength: " + this.outLength.toInt32());
            // console.log("outCount: " + Memory.readUInt(this.outCountPtr)); //实际的outBuffer的有效长度

            // console.log("[+] CCAlgorithm: " + this.CCAlgorithm);
            if (this.CCAlgorithm == 0x0) { console.log("[+] CCAlgorithm: " + this.CCAlgorithm + " --> AES Decrypt"); }
            if (this.CCAlgorithm == 0x1) { console.log("[+] CCAlgorithm: " + this.CCAlgorithm + " --> DES Decrypt"); }
            if (this.CCAlgorithm == 0x2) { console.log("[+] CCAlgorithm: " + this.CCAlgorithm + " --> 3DES Decrypt"); }

            // enum {
            //     /* options for block ciphers */
            //     kCCOptionPKCS7Padding   = 0x0001,
            //     kCCOptionECBMode        = 0x0002
            //     /* stream ciphers currently have no options */
            // };
            // typedef uint32_t CCOptions;
            if (this.CCOptions == 0x0 || this.CCOptions == 0x1) { console.log("[+] CCOptions: " + this.CCOptions + " --> mode CBC"); }
            if (this.CCOptions == 0x2 || this.CCOptions == 0x3) { console.log("[+] CCOptions: " + this.CCOptions + " --> mode ECB"); } // kCCOptionPKCS7Padding | kCCOptionECBMode == 0x03
            // if (this.CCOptions != 0x1 && this.CCOptions != 0x3) {console.log("[+] CCOptions: " + this.CCOptions);}

            var array = new Uint8Array(Memory.readByteArray(this.inBuffer, this.inLength.toInt32()));
            // console.log("[+] Before Decrypt: " + base64encode(bin2string(array)));
            LOG("[+] Before Decrypt: " + base64encode(bin2string(array)), { c: Color.Gray });

            console.log(Memory.readByteArray(this.keyBytes, this.keyLength.toInt32()));
            if (this.keyLength.toInt32() == 16) { console.log("[+] KEY Length --> 128"); }
            if (this.keyLength.toInt32() == 24) { console.log("[+] KEY Length --> 192"); }
            if (this.keyLength.toInt32() == 32) { console.log("[+] KEY Length --> 256"); }
            try {
                // console.log("[+] KEY: " + Memory.readUtf8String(this.keyBytes, this.keyLength.toInt32()));
                LOG("[+] KEY: " + Memory.readUtf8String(this.keyBytes, this.keyLength.toInt32()), { c: Color.Gray });
            } catch (e) {
                var ByteArray = Memory.readByteArray(this.keyBytes, this.keyLength.toInt32());
                var uint8Array = new Uint8Array(ByteArray);
                // console.log("[+] uint8Array: " + uint8Array);

                var str = "";
                for (var i = 0; i < uint8Array.length; i++) {
                    var hextemp = (uint8Array[i].toString(16))
                    if (hextemp.length == 1) {
                        hextemp = "0" + hextemp
                    }
                    str += hextemp + " ";
                }

                // console.log("[+] KEY: " + str); // 打印hex,非可见ascii范围
                LOG("[+] KEY: " + str, { c: Color.Gray });
            }

            if (this.CCOptions == 0x0 || this.CCOptions == 0x1) {
                console.log(Memory.readByteArray(this.ivBuffer, 16));
                try {
                    // console.log("[+] IV: " + Memory.readUtf8String(this.ivBuffer, this.keyLength.toInt32()));
                    LOG("[+] IV: " + Memory.readUtf8String(this.ivBuffer, 16), { c: Color.Gray });
                } catch (e) {
                    var ByteArray = Memory.readByteArray(this.ivBuffer, 16);
                    var uint8Array = new Uint8Array(ByteArray);

                    var str = "";
                    for (var i = 0; i < uint8Array.length; i++) {
                        var hextemp = (uint8Array[i].toString(16))
                        if (hextemp.length == 1) {
                            hextemp = "0" + hextemp
                        }
                        str += hextemp + " ";
                    }

                    // console.log("[+] IV: " + str); // 打印hex,非可见ascii范围
                    LOG("[+] IV: " + str, { c: Color.Gray });
                }
            }

            console.log(Memory.readByteArray(this.outBuffer, Memory.readUInt(this.outCountPtr)));
            try {
                // console.log("[+] After Decrypt: " + Memory.readUtf8String(this.outBuffer, Memory.readUInt(this.outCountPtr)));
                LOG("[+] After Decrypt: " + Memory.readUtf8String(this.outBuffer, Memory.readUInt(this.outCountPtr)), { c: Color.Gray });
            } catch (e) {
                // var ByteArray = Memory.readByteArray(this.outBuffer, Memory.readUInt(this.outCountPtr));
                // var uint8Array = new Uint8Array(ByteArray);
                // // console.log("[+] uint8Array: " + uint8Array);

                // var str = "";
                // for(var i = 0; i < uint8Array.length; i++) {
                //     var hextemp = (uint8Array[i].toString(16))
                //     if(hextemp.length == 1){
                //         hextemp = "0" + hextemp
                //     }
                //         str += hextemp + " ";
                // }

                // console.log("[+] After Decrypt: " + str); // 打印hex,非可见ascii范围
            }
            }
        log('CCCrypt() 🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼\n');
    }
});
