/*
 * Auto-generated by Frida. Please modify to match the signature of CCHmac.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
    onEnter(log, args, state) {
        log('CCHmac() 🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽');
        // 解析算法类型
        var alg = args[0].toInt32 ? args[0].toInt32() : parseInt(args[0]);
        var algName = '';
        var digestLen = 0;
        switch (alg) {
            case 0x0: algName = 'kCCHmacAlgSHA1'; digestLen = 20; break;
            case 0x1: algName = 'kCCHmacAlgMD5'; digestLen = 16; break;
            case 0x2: algName = 'kCCHmacAlgSHA256'; digestLen = 32; break;
            case 0x4: algName = 'kCCHmacAlgSHA512'; digestLen = 64; break;
            default: algName = 'Unknown'; digestLen = 0;
        }
        log('Algorithm: ' + alg + ' --> ' + algName);
        // 解析key
        var keyLen = args[2].toInt32 ? args[2].toInt32() : parseInt(args[2]);
        try {
            log('key: ' + Memory.readUtf8String(args[1], keyLen));
        } catch (e) {
            log('key(hex):');
            log(hexdump(args[1], { length: keyLen }));
        }
        // 解析输入数据
        var dataLen = args[4].toInt32 ? args[4].toInt32() : parseInt(args[4]);
        try {
            log('input: ' + Memory.readUtf8String(args[3], dataLen));
        } catch (e) {
            log('input(hex):');
            log(hexdump(args[3], { length: dataLen }));
        }
    },

    onLeave(log, retval, state) {
        // 输出HMAC结果
        var digestLen = state && state.digestLen ? state.digestLen : 32;
        var hmac_digest = hexdump(retval, {length: digestLen});
        var hexified = " ";
        var raw_array = hmac_digest.split("\n");
        for (var a = 0; a < raw_array.length; a++) {
            var line_array = raw_array[a].split(" ");
            for (var b = 1; b < line_array.length - 1; b++) {
                if (line_array[b].length === 2) {
                    hexified += line_array[b];
                    hexified = hexified.trim();
                }
            }
        }
        log('output: ' + hexified);
        log('CCHmac() 🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼🔼\n');
    }
});
