/*
 * Auto-generated by Frida. Please modify to match the signature of getpeername.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`getpeername(socket=${args[0]}, address=${args[1]}, address_len=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
